app/models.py
from . import db
from werkzeug.security import generate_password_hash,check_password_hash
from flask_login import UserMixin
from . import login_manager
from datetime import datetime



@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))


class User(UserMixin,db.Model):
    __tablename__ = 'users'
    id = db.Column(db.Integer,primary_key = True)
    username = db.Column(db.String(255),index = True)
    email = db.Column(db.String(255),unique = True,index = True)
    bio = db.Column(db.String(255))
    profile_pic_path = db.Column(db.String())
    pass_secure = db.Column(db.String(255))
    comments = db.relationship('Comment',backref = 'comments',lazy = "dynamic")

    @property  
    def password(self): 
        raise AttributeError('You cannot read the password attribute') 


    @password.setter 
    def password(self, password):   
        self.pass_secure = generate_password_hash(password)   

    def verify_password(self,password):   
        return check_password_hash(self.pass_secure,password)


    def __repr__(self):
        return f'User {self.username}'




class Blog(UserMixin,db.Model):

    __tablename__ = 'blogs'

    id = db.Column(db.Integer, primary_key=True)
    user = db.Column(db.String(255))
    heading = db.Column(db.String(255))
    blog = db.Column(db.String(1000))
    date_posted = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)
    user_id = db.Column(db.Integer, db.ForeignKey("users.id"))
   
    
    def save_blog(self):
        db.session.add(self)
        db.session.commit()        




class Comment(UserMixin,db.Model):

    __tablename__ = 'comments'

    id = db.Column(db.Integer, primary_key=True)
    user = db.Column(db.String(255))
    comment = db.Column(db.String(10000))
    date_posted = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)
    user_id = db.Column(db.Integer, db.ForeignKey("users.id"))
    
   
    
    def save_comment(self):
        db.session.add(self)
        db.session.commit()        


    def delete_comment(self, comment):
        db.session.delete(comment)
        db.session.commit()

app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField,TextAreaField,SubmitField
from wtforms.validators import Required



class BlogForm(FlaskForm):

    user = StringField('Your name',validators=[Required()])

    heading = StringField('Blog Heading',validators=[Required()])

    blog = TextAreaField('Your blog',validators=[Required()])
    
    submit = SubmitField('Post')


class CommentForm(FlaskForm):

    user = StringField('Your name',validators=[Required()])

    comment = TextAreaField('Your comment',validators=[Required()])
    
    submit = SubmitField('Comment')


class UpdateProfile(FlaskForm):
    bio = TextAreaField('Tell us about you.',validators = [Required()])
    submit = SubmitField('Submit')   

class DeletePost(FlaskForm):
    comment_id = StringField()
    delete = SubmitField('Delete')

app/__init__.py
from flask import Flask
from flask import Blueprint
from config import config_options
from config import Config
from flask_bootstrap import Bootstrap
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
from flask_uploads import UploadSet,configure_uploads,IMAGES
from flask_mail import Mail
from flask_simplemde import SimpleMDE

login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.login'


bootstrap = Bootstrap()
db = SQLAlchemy()
photos = UploadSet('photos',IMAGES)
mail = Mail()
simple = SimpleMDE()

# Initializing application
def create_app(config_name):
    app = Flask(__name__)


     # Creating the app configurations
    app.config.from_object(config_options[config_name])
    app.config.from_object(Config)

    # configure UploadSet
    configure_uploads(app,photos)

   # initializing flask extensions
   
    bootstrap.init_app(app)
    db.init_app(app)
    login_manager.init_app(app)
    mail.init_app(app)
    simple.init_app(app)

 # Registering blueprints
    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)
    from .auth import auth as auth_blueprint 
    app.register_blueprint(auth_blueprint,url_prefix = '/authenticate')

    '''
    Here I register my blue prints
    '''

    #setting config
    return app

app/main/__init__.py
from flask import Blueprint
main = Blueprint('main',__name__)
from . import views,forms,error

app/main/views.py
from flask import render_template,request,redirect,url_for,abort
from . import main
from .forms import CommentForm,BlogForm, DeletePost
from flask_login import login_required, current_user
from .. import auth
from ..models import User,Comment,Blog
from .forms import UpdateProfile
from .. import db,photos
import markdown2
from ..email import mail_message


@main.route('/')

def index():
    '''
    View root page function that returns index page and its data
    '''
    title = 'BLOG MANENOS'

    

    return render_template('index.html', title = title, index = index)



@main.route('/comment' , methods = ['GET','POST'])
@login_required
def comment():
    form = CommentForm() 
    del_form = DeletePost()
    if form.validate_on_submit():
        comment = Comment(user=form.user.data,comment=form.comment.data)
        comment.save_comment()
        
        return redirect(url_for('main.comment'))
    elif del_form.validate_on_submit():
        
        comment_id = del_form.comment_id.data
        comment= Comment.query.filter_by(comment=comment_id).first()
        if comment:
            
            comment.delete_comment(comment)
        return redirect(url_for('main.comment'))
        
    comments=Comment.query.all()

    return render_template('comment.html', form = form ,comments=comments, del_form=del_form)    


@main.route('/blog' , methods = ['GET','POST'])
@login_required
def blog():
    form = BlogForm() 
    if form.validate_on_submit():
        blog = Blog(user=form.user.data,blog=form.blog.data,heading=form.heading.data)
        blog.save_blog()
        user=User.query.all()
        for email in user:
            mail_message("Blog updates","email/subscription",email.email,user=user)
        return redirect(url_for('main.blog'))
        
    posts=Blog.query.all()

    return render_template('blog.html',posts=posts, form = form )     




@main.route('/user/<uname>')
def profile(uname):
    user = User.query.filter_by(username = uname).first()

    if user is None:
        abort(404)

    return render_template("profile/profile.html", user = user)


@main.route('/user/<uname>/update',methods = ['GET','POST'])
@login_required
def update_profile(uname):
    user = User.query.filter_by(username = uname).first()
    if user is None:
        abort(404)

    form = UpdateProfile()

    if form.validate_on_submit():
        user.bio = form.bio.data

        db.session.add(user)
        db.session.commit()

        return redirect(url_for('.profile',uname=user.username))

    return render_template('profile/update.html',form =form)



@main.route('/user/<uname>/update/pic',methods= ['POST'])
@login_required
def update_pic(uname):
    user = User.query.filter_by(username = uname).first()
    if 'photo' in request.files:
        filename = photos.save(request.files['photo'])
        path = f'photos/{filename}'
        user.profile_pic_path = path
        db.session.commit()
    return redirect(url_for('main.profile',uname=uname))

app/templates/base.html
{% extends 'bootstrap/base.html'%}

<!-- Navbar block  --> 
{% block navbar %}
    {% include 'navbar.html' %}
{% endblock %}

{%block styles %}
  {{super()}}
  <!--Importing the simple mde css and js files  -->
  {{ simplemde.css}}
  {{ simplemde.js }}

{% endblock %}

app/templates/blog.html
{% extends 'base.html'%} {% import "bootstrap/wtf.html" as wtf %} {% block content %}
<div class="container">
    <a href="/"><i class="glyphicon glyphicon-menu-left"></i>Back</a>
    <div class="row">
            <div class="jumbotron" style="text-align:center">
                    <p >These are more blogs from different people.</p>
                    <p>You can as well add your blog here.</p>
                </div>

            <div class="col-md-8">
        {% for blog in posts %}
        
        
        <div class="panel panel-success panel-body">
                <div class="panel panel-success panel-heading">  
               
            <h2 style="text-align:center">{{blog.heading}}</h2>
            </div> 
      
        <p>  {{blog.blog}}</p>    
     <p>By:{{ blog.user }}</p>
        
        <div class="card-footer">
        <p>{{ blog.date_posted }}</p>
    </div>
    <a href="/comment"><i class="glyphicon glyphicon-comment"></i></a>
    </div>

        {% endfor %}
        </div>
        
        <div class="col-md-4">
            <a class="btn btn-primary" data-toggle="collapse" href="#multiCollapseExample1" role="button" aria-expanded="false" aria-controls="multiCollapseExample1"><i class="glyphicon glyphicon-plus"></i>Add blog</a>

            <div class="collapse multi-collapse" id="multiCollapseExample1" style=" padding:30px;">
                <div class="card card-body">
                    {{ wtf.quick_form(form) }}
                    
                   
                </div>
            </div>


        </div>


    </div>
</div>

{% endblock %}

app/templates/comment.html
{% extends 'base.html'%} {% import "bootstrap/wtf.html" as wtf %} {% block content %}
<div class="container">
    <h2 style="text-align:center">Comments</h2>

    <div class="row">

        <div class="col-md-8">
            {% for comment in comments %}
            <div class="panel panel-primary panel-heading">

        <p> {{comment.comment}}</p>
       <p> By:{{ comment.user }}</p>
      <p>{{ comment.date_posted }}</p>


      <form action="" method="POST">
          {{ del_form.csrf_token }}
          {{ del_form.comment_id(class='d-none', value=comment.comment) }}
          {{ del_form.delete(class='btn btn-danger') }}
      </form>


            </div>

            {% endfor %}
        </div>
        <a class="btn btn-primary" data-toggle="collapse" href="#multiCollapseExample1" role="button" aria-expanded="false" aria-controls="multiCollapseExample1">Comment</a>

        <div class="col-md-4">
            <div class="collapse multi-collapse" id="multiCollapseExample1">

                {{ wtf.quick_form(form) }}

            </div>


        </div>


    </div>
</div>

{% endblock %}

app/templates/fourOwfour.html
{% block content %}
<img src="https://cdn.mos.cms.futurecdn.net/PuXipAW3AXUzUJ4uYyxPKC.jpg" height="600px" width="1360px" alt="">
{% endblock %}

app/templates/navbar.html
<link href="https://fonts.googleapis.com/css?family=Fontdiner+Swanky" rel="stylesheet">


<div class="navbar navbar-inverse" role="navigation" style="background-color: rgb(17, 17, 8);">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>

            </button>
            <a class="navbar-brand" href="/"></a>

        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li style="font-size:20px;"><a href="/"><span class="glyphicon glyphicon-home"></span>Home</a></li>

        </div>

        <ul class="nav navbar-nav navbar-right">
            {% if current_user.is_authenticated %}
            <li style="color:white;padding:18px;font-family: 'Fontdiner Swanky', cursive;">
                <H3>{{current_user.username}}</H3>
            </li>
            <li class="pro"><a href="{{url_for('main.profile',uname=current_user.username)}}"><H3><i class="glyphicon glyphicon-cog"></i>Settings</H3></a></li>
            <li><a href="{{url_for('auth.logout')}}"><H3>Sign out</H3></a></li>
            {% else %}
            <li><a href="{{url_for('auth.register')}}"><H3>Subscribe</H3></a></li>
            <li><a href="{{url_for('auth.login')}}"><H3><i class="glyphicon glyphicon-log-in"></i>Log in</H3></a></li>
            {%endif%}
        </ul>



    </div>

</div>

<style>
    #pro {
        font-family: 'Cookie', cursive;
        font-size: 30px;
    }
</style>

app/templates/profile/profile.html
{% extends 'base.html'%}

{% block content %}
<div class="container">
<div class="row">
<!-- displaying  Username-->
  <div class="col-md-4">
    <h3> {{user.username| capitalize}} </h3>

    <!--Displaying user bio-->
    {% if user.bio %}
      <p> {{user.bio}}</p>
    {%else%}
      <p> {{user.username| capitalize}} has no bio </p>
    {% endif %}
    {% if user == current_user %}
    <a href="{{url_for('main.update_profile',uname=user.username)}}">Edit profile</a>
{% endif %}
  </div>

  <!--Display profile photo-->
  <div class="col-md-4">

    {% if user.profile_pic_path %}
    <img src="{{url_for('static',filename=user.profile_pic_path)}}" alt="" class="img-thumbnail">
    {%else%}
    <p>No profile picture</p>
    {% endif %}
  </div>
  {% if user == current_user %}
  <form  action="{{url_for('main.update_pic',uname=user.username)}}" method="post" enctype = "multipart/form-data">

    <input type="file"  name="photo"  required>
    <input type="submit">
  </form>
    {% endif %}
</div>
</div>



{% endblock %}

app/templates/profile/update.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block content %}
<div class="container">
  {{wtf.quick_form(form)}}
</div>
{% endblock %}